export const YCM_TEAM_FUNCTIONS = [
  'sales',
  'operations',
  'field',
  'document',
  'support',
  'legal',
  'education',
  'finance',
  'customer',
  'agriculture',
  'farmer',
  'fpo',
  'dairy',
  'kirana',
  'insurance',
  'loans',
  'banking',
  'aeps',
  'business',
  'msme',
  'tax',
  'compliance',
  'crm',
  'telecalling',
  'digital',
  'technology',
  'content',
  'marketing',
  'partnerships',
  'franchise',
  'training',
  'quality',
  'verification',
  'grievance',
  'legal_operations',
  'custom',
] as const;

export type YcmTeamFunction = typeof YCM_TEAM_FUNCTIONS[number];

export const YCM_BUSINESS_DOMAINS = [
  'government-services-schemes',
  'documents-certificates',
  'education-admission-scholarship',
  'jobs-employment-internship',
  'business-startup-msme',
  'loans-finance-insurance',
  'tax-gst-accounting',
  'legal-documentation',
  'property-land',
  'court-authority-process',
  'health-medical-discovery',
  'travel-passport-visa-immigration',
  'overseas-education-employment',
  'women-children-senior',
  'disability-social-welfare',
  'agriculture-farmer',
  'labour-worker',
  'pension',
  'banking-financial-services',
  'digital-services',
  'utility-services',
  'consumer-grievances',
  'police-public-grievance',
  'municipal-local-body',
  'ngo-social-assistance',
  'professional-services',
  'corporate-business-services',
  'international-citizen-resident',
  'transport-mobility',
  'food-nutrition',
  'skills-vocational-training',
  'housing-urban-development',
  'environment-climate',
  'public-safety-emergency',
  'youth-sports-culture',
] as const;

export type YcmBusinessDomain = typeof YCM_BUSINESS_DOMAINS[number];
export const YCM_BUSINESS_DOMAIN_COUNT = YCM_BUSINESS_DOMAINS.length;
