/* eslint-disable @typescript-eslint/no-explicit-any, react-hooks/exhaustive-deps */
'use client';
import {useEffect,useState} from 'react';

type ServiceForm={serviceCode:string;serviceName:string;serviceType:string;businessDomainCode:string;parentServiceCode:string;channel:string;requiresCase:boolean;requiresDocuments:boolean;requiresProvider:boolean;status:string;validityDays:string|number;expiryWarningDays:string|number;renewalAllowed:boolean;renewalWindowDays:string|number;prefillFields:string;documentRequirements:string};
type Service={service_code:string;service_name:string;service_type:string;business_domain_code?:string|null;parent_service_code?:string|null;channel?:string;requires_case:boolean;requires_documents:boolean;requires_provider:boolean;status:string;validity_days?:number|null;expiry_warning_days?:number;renewal_allowed?:boolean;renewal_window_days?:number;prefill_fields?:unknown[];metadata?:Record<string,unknown>};
const blank={serviceCode:'',serviceName:'',serviceType:'other',businessDomainCode:'',parentServiceCode:'',channel:'assisted',requiresCase:true,requiresDocuments:false,requiresProvider:false,status:'draft',validityDays:'',expiryWarningDays:'30',renewalAllowed:true,renewalWindowDays:'60',prefillFields:'full_name,mobile,email,date_of_birth,relation',documentRequirements:'[]'};

export default function ServiceMasterPage(){
 const [rows,setRows]=useState<Service[]>([]),[q,setQ]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[editing,setEditing]=useState<Service|null>(null),[form,setForm]=useState<ServiceForm>({...blank});
 const load=async()=>{setLoading(true);setError('');try{const r=await fetch('/api/service-master?includeAll=true&q='+encodeURIComponent(q),{cache:'no-store'});const j=await r.json();if(!r.ok)throw Error(j.message||j.code||'SERVICE_CATALOG_UNAVAILABLE');setRows(j.services||[]);}catch(e){setError(e instanceof Error?e.message:'SERVICE_CATALOG_UNAVAILABLE');}finally{setLoading(false);}};
 useEffect(()=>{const id=window.setTimeout(()=>void load(),250);return()=>window.clearTimeout(id);},[q]);
 const reset=()=>{setEditing(null);setForm({...blank});setMessage('');};
 const edit=async(s:Service)=>{setEditing(s);setForm(v=>({...v,serviceCode:s.service_code,serviceName:s.service_name,serviceType:s.service_type,businessDomainCode:s.business_domain_code||'',parentServiceCode:s.parent_service_code||'',channel:s.channel||'assisted',requiresCase:s.requires_case,requiresDocuments:s.requires_documents,requiresProvider:s.requires_provider,status:s.status,validityDays:s.validity_days??'',expiryWarningDays:s.expiry_warning_days??30,renewalAllowed:s.renewal_allowed!==false,renewalWindowDays:s.renewal_window_days??60,prefillFields:Array.isArray(s.prefill_fields)?s.prefill_fields.map((x:any)=>typeof x==='string'?x:x?.field||'').join(','):v.prefillFields}));setMessage('');try{const r=await fetch('/api/service-master?serviceCode='+encodeURIComponent(s.service_code),{cache:'no-store'});const j=await r.json();if(r.ok&&j.documents)setForm(v=>({...v,documentRequirements:JSON.stringify(j.documents.map((d:any)=>({documentCode:d.document_code,documentName:d.document_name,required:d.required,requiredForApplication:d.required_for_application,validationMode:d.validation_mode,validityDays:d.validity_days,expiryWarningDays:d.expiry_warning_days,reuseIfValid:d.reuse_if_valid,reuploadOnExpiry:d.reupload_on_expiry,prefillFields:d.prefill_fields,sourceName:d.source_name,sourceUrl:d.source_url})),null,2)}));}catch{} };
 const save=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);setError('');setMessage('');try{let documentRequirements:any[]=[];
try{documentRequirements=JSON.parse(String(form.documentRequirements||'[]'));if(!Array.isArray(documentRequirements))throw new Error('Document requirements must be a JSON array.');}catch{setError('Document requirements JSON is invalid.');setSaving(false);return;}
const payload={...form,validityDays:form.validityDays===''?null:Number(form.validityDays),expiryWarningDays:Number(form.expiryWarningDays),renewalWindowDays:Number(form.renewalWindowDays),renewalAllowed:Boolean(form.renewalAllowed),prefillFields:String(form.prefillFields).split(',').map(x=>x.trim()).filter(Boolean),documentRequirements,metadata:{managedFrom:'service-master-ui'}};const r=await fetch('/api/service-master',{method:editing?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const j=await r.json();if(!r.ok)throw Error(j.message||j.code||'SERVICE_SAVE_FAILED');setMessage(editing?'Service updated successfully.':'Service created successfully.');reset();await load();}catch(e){setError(e instanceof Error?e.message:'SERVICE_SAVE_FAILED');}finally{setSaving(false);}};
 return <main className="min-h-screen bg-slate-50 text-slate-900"><header className="bg-slate-950 text-white"><div className="mx-auto max-w-7xl px-5 py-8"><div className="text-xs font-black uppercase tracking-[.2em] text-cyan-300">YCM ONE • SERVICE GOVERNANCE</div><h1 className="mt-2 text-3xl font-black md:text-5xl">Service Master</h1><p className="mt-2 max-w-3xl text-slate-300">CEO / Management / Admin can add and edit the canonical service catalog without changing frontend code.</p></div></header>
 <section className="mx-auto grid max-w-7xl gap-5 px-5 py-7 lg:grid-cols-[1.5fr_.8fr]">
  <div className="rounded-3xl border bg-white p-5 shadow-sm"><div className="flex flex-col justify-between gap-3 md:flex-row md:items-center"><div><h2 className="text-2xl font-black">Catalog</h2><p className="text-sm text-slate-500">{rows.length} services loaded</p></div><div className="flex gap-2"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search service…" className="w-64 rounded-xl border px-3 py-2 text-sm"/><button onClick={()=>void load()} className="rounded-xl border px-4 py-2 text-xs font-black">Refresh</button></div></div>
   {error&&<div className="mt-4 rounded-xl bg-red-50 p-3 text-sm font-bold text-red-700">{error}</div>}{message&&<div className="mt-4 rounded-xl bg-emerald-50 p-3 text-sm font-bold text-emerald-700">{message}</div>}
   <div className="mt-5 overflow-x-auto"><table className="w-full min-w-[1050px] text-left text-xs"><thead><tr className="border-b text-slate-500"><th className="p-3">Code</th><th className="p-3">Service</th><th className="p-3">Type</th><th className="p-3">Domain</th><th className="p-3">Channel</th><th className="p-3">Case</th><th className="p-3">Docs</th><th className="p-3">Provider</th><th className="p-3">Status</th><th className="p-3">Action</th></tr></thead><tbody>{rows.map(s=><tr key={s.service_code} className="border-b hover:bg-slate-50"><td className="p-3 font-black">{s.service_code}</td><td className="p-3">{s.service_name}</td><td className="p-3">{s.service_type}</td><td className="p-3">{s.business_domain_code||'—'}</td><td className="p-3">{s.channel||'—'}</td><td className="p-3">{s.requires_case?'Yes':'No'}</td><td className="p-3">{s.requires_documents?'Yes':'No'}</td><td className="p-3">{s.requires_provider?'Yes':'No'}</td><td className="p-3"><span className="rounded-full bg-slate-100 px-2 py-1 font-bold">{s.status}</span></td><td className="p-3"><button onClick={()=>edit(s)} className="rounded-lg border px-3 py-1 font-black">Edit</button></td></tr>)}</tbody></table>{loading&&<div className="p-5 text-sm text-slate-500">Loading service catalog…</div>}{!loading&&!rows.length&&<div className="p-5 text-sm text-slate-500">No services found.</div>}</div>
  </div>
  <form onSubmit={save} className="rounded-3xl border bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="text-2xl font-black">{editing?'Edit service':'Add service'}</h2><p className="text-sm text-slate-500">Database-driven, no code deploy needed.</p></div>{editing&&<button type="button" onClick={reset} className="rounded-xl border px-3 py-2 text-xs font-black">New</button>}</div>
   <div className="mt-5 space-y-3">{[['serviceCode','Service code'],['serviceName','Service name'],['serviceType','Service type'],['businessDomainCode','Business domain'],['parentServiceCode','Parent service'],['channel','Channel']].map(([key,label])=><label key={key} className="block"><span className="mb-1 block text-xs font-black text-slate-500">{label}</span><input disabled={Boolean(editing)&&key==='serviceCode'} value={(form as any)[key]} onChange={e=>setForm(v=>({...v,[key]:e.target.value}))} className="w-full rounded-xl border px-3 py-2 text-sm disabled:bg-slate-100" required={key==='serviceCode'||key==='serviceName'}/></label>)}
   <label className="block"><span className="mb-1 block text-xs font-black text-slate-500">Status</span><select value={form.status} onChange={e=>setForm(v=>({...v,status:e.target.value}))} className="w-full rounded-xl border px-3 py-2 text-sm"><option value="draft">Draft</option><option value="active">Active</option><option value="retired">Retired</option></select></label>
   <div className="grid gap-3 md:grid-cols-2">
<label className="block"><span className="mb-1 block text-xs font-black text-slate-500">Validity (days)</span><input type="number" min="0" value={(form as any).validityDays} onChange={e=>setForm(v=>({...v,validityDays:e.target.value}))} placeholder="Blank = authority/not applicable" className="w-full rounded-xl border px-3 py-2 text-sm"/></label>
<label className="block"><span className="mb-1 block text-xs font-black text-slate-500">Expiry warning (days)</span><input type="number" min="0" value={(form as any).expiryWarningDays} onChange={e=>setForm(v=>({...v,expiryWarningDays:e.target.value}))} className="w-full rounded-xl border px-3 py-2 text-sm"/></label>
<label className="block"><span className="mb-1 block text-xs font-black text-slate-500">Renewal window (days)</span><input type="number" min="0" value={(form as any).renewalWindowDays} onChange={e=>setForm(v=>({...v,renewalWindowDays:e.target.value}))} className="w-full rounded-xl border px-3 py-2 text-sm"/></label>
<label className="flex items-center gap-2 rounded-xl border p-3 text-xs font-bold"><input type="checkbox" checked={Boolean((form as any).renewalAllowed)} onChange={e=>setForm(v=>({...v,renewalAllowed:e.target.checked}))}/> Renewal allowed</label>
</div>
<label className="block"><span className="mb-1 block text-xs font-black text-slate-500">Apply-time prefill fields (comma separated)</span><input value={(form as any).prefillFields} onChange={e=>setForm(v=>({...v,prefillFields:e.target.value}))} className="w-full rounded-xl border px-3 py-2 text-sm" placeholder="full_name,mobile,date_of_birth"/></label>
<label className="block"><span className="mb-1 block text-xs font-black text-slate-500">Document requirements JSON</span><textarea rows={8} value={(form as any).documentRequirements} onChange={e=>setForm(v=>({...v,documentRequirements:e.target.value}))} className="w-full rounded-xl border px-3 py-2 font-mono text-xs" placeholder='[{"documentCode":"AADHAAR","documentName":"Aadhaar Card","required":true,"validityDays":3650,"reuseIfValid":true,"reuploadOnExpiry":true}]'/><span className="mt-1 block text-[11px] text-slate-500">Existing verified + valid documents are reused automatically; expired/missing ones appear for upload.</span></label>
<div className="grid grid-cols-3 gap-2">{[['requiresCase','Case'],['requiresDocuments','Documents'],['requiresProvider','Provider']].map(([key,label])=><label key={key} className="flex items-center gap-2 rounded-xl border p-3 text-xs font-bold"><input type="checkbox" checked={Boolean((form as any)[key])} onChange={e=>setForm(v=>({...v,[key]:e.target.checked}))}/>{label}</label>)}</div>
   <button disabled={saving} className="w-full rounded-xl bg-slate-950 px-4 py-3 text-sm font-black text-white disabled:opacity-50">{saving?'Saving…':editing?'Update service':'Create service'}</button>
   <p className="text-xs leading-5 text-slate-500">Provider credentials, API keys and secrets must remain in deployment secrets/secret manager, never in this catalog.</p>
  </div></form>
 </section></main>;
}