'use client';
import {useEffect,useRef,useState} from 'react';
export default function MitraPage(){
 const [text,setText]=useState(''),[list,setList]=useState<any[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const rec=useRef<any>(null);
 useEffect(()=>()=>rec.current?.stop?.(),[]);
 const speak=(v:string)=>{if(!('speechSynthesis' in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(v);u.lang='hi-IN';window.speechSynthesis.speak(u)};
 const search=async(v=text)=>{if(!v.trim())return;setBusy(true);setError('');try{const r=await fetch('/api/ai-mitra/voice',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:v})});const j=await r.json();if(!r.ok)throw Error(j.code||'VOICE_SEARCH_FAILED');setList(j.services||[]);speak(j.services?.length?'आपकी जरूरत के लिए services मिली हैं।':'अभी exact service नहीं मिली। कृपया थोड़ा और बताएं।')}catch(e){setError(e instanceof Error?e.message:'VOICE_SEARCH_FAILED')}finally{setBusy(false)}};
 const listen=()=>{const SR=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!SR){setError('इस device/browser में voice input उपलब्ध नहीं है। Text से भी इस्तेमाल कर सकते हैं।');return}const r=new SR();r.lang='hi-IN';r.interimResults=false;r.onresult=(e:any)=>{const v=e.results?.[0]?.[0]?.transcript||'';setText(v);void search(v)};r.onerror=()=>setError('आवाज़ समझ नहीं आई। फिर से बोलें।');rec.current=r;r.start()};
 return <main className="min-h-screen bg-slate-50"><header className="bg-slate-950 text-white"><div className="mx-auto max-w-4xl px-5 py-10"><div className="text-xs font-black tracking-[.2em] text-cyan-300">YCM ONE • MITRA</div><h1 className="mt-2 text-4xl font-black">बस अपनी जरूरत बोलिए</h1><p className="mt-3 text-slate-300">Loan, scholarship, scheme, document, farmer, business, job, legal या कोई भी service पूछें।</p></div></header><section className="mx-auto max-w-4xl px-5 py-8"><div className="rounded-3xl border bg-white p-6 shadow-sm"><button onClick={listen} className="mx-auto flex h-24 w-24 items-center justify-center rounded-full bg-slate-900 text-4xl text-white">🎙️</button><p className="mt-3 text-center text-sm font-bold">{busy?'खोज रहा हूँ…':'बटन दबाकर बोलें'}</p><div className="mt-5 flex gap-2"><input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void search()}} placeholder="जैसे: मुझे बिजनेस लोन चाहिए" className="flex-1 rounded-2xl border px-4 py-3"/><button onClick={()=>void search()} className="rounded-2xl bg-slate-900 px-5 font-black text-white">खोजें</button></div>{error&&<p className="mt-3 rounded-xl bg-red-50 p-3 text-sm font-bold text-red-700">{error}</p>}</div>{list.length>0&&<div className="mt-6 space-y-4">{list.map(s=><article key={s.service_code} className="rounded-3xl border bg-white p-5 shadow-sm"><div className="text-xs font-black uppercase text-slate-500">{s.service_type} • {s.business_domain_code}</div><h2 className="mt-1 text-xl font-black">{s.service_name}</h2><div className="mt-4 grid gap-4 md:grid-cols-2"><div><b>Documents</b>{s.documents?.length?<ul className="mt-2 list-disc pl-5 text-sm">{s.documents.slice(0,8).map((d:any)=><li key={d.documentCode}>{d.documentName}{d.required?' *':''}</li>)}</ul>:<p className="text-sm text-slate-500">अभी configure नहीं हैं।</p>}</div><div><b>YCM सहायता</b><p className="mt-2 text-sm">Eligibility, documents, application preparation और case tracking workflow के अनुसार।</p>{s.pricing?.length?<p className="mt-2 font-bold">Configured charge: {s.pricing[0].customerPrice} {s.pricing[0].currency||'INR'}</p>:<p className="text-sm text-slate-500">Charge अभी configure नहीं है।</p>}</div></div><div className="mt-4 flex flex-wrap gap-2">{s.documents?.filter((d:any)=>d.sourceUrl).slice(0,3).map((d:any)=><a key={d.documentCode} href={d.sourceUrl} target="_blank" rel="noreferrer" className="rounded-xl border px-3 py-2 text-xs font-black">Official source ↗</a>)}<button onClick={()=>speak('Eligibility और application process देखने के लिए आगे बढ़ें।')} className="rounded-xl bg-slate-100 px-3 py-2 text-xs font-black">🔊 सुनें</button></div><p className="mt-4 rounded-2xl bg-amber-50 p-3 text-xs">Official eligibility/approval संबंधित authority पर निर्भर है।</p></article>)}</div>}</section></main>
}
