'use client';
import {useEffect,useState} from 'react';
import {YCM_LIFECYCLE,YCM_MODULES,YCMModule,ModuleStatus} from '../ycm-architecture';
const statusLabel:Record<ModuleStatus,string>={live:'Live',partial:'Partial',planned:'Planned'};
const statusClass:Record<ModuleStatus,string>={live:'bg-emerald-50 text-emerald-700 border-emerald-200',partial:'bg-amber-50 text-amber-700 border-amber-200',planned:'bg-slate-100 text-slate-600 border-slate-200'};
const sections=['Platform Overview','Operations','Family 360','Services','Documents','Education','Agriculture','Finance/Commission','AEPS','CRM/Leads','Impact & Proof','Integrations','Security/Audit','Reports'];
export default function CommandCenterPage(){
 type Assignment={status:string}; type ImpactRow={outcomes_verified?:number}; type Health={ready:boolean;databaseConfigured:boolean;tables:{table:string;exists:boolean}[];code?:string};
 const [assignments,setAssignments]=useState<Assignment[]>([]),[opsError,setOpsError]=useState(''),[impact,setImpact]=useState<ImpactRow[]|null>(null),[impactError,setImpactError]=useState(''),[health,setHealth]=useState<Health|null>(null),[healthError,setHealthError]=useState('');
 useEffect(()=>{fetch('/api/work-assignments?mine=false',{cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.code||'OPERATIONS_QUEUE_UNAVAILABLE');setAssignments(d.assignments||[])}).catch(e=>setOpsError(e.message));fetch('/api/impact-proof?verified=true',{cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.code||'IMPACT_DATA_UNAVAILABLE');setImpact(d.rows||[])}).catch(e=>setImpactError(e.message));fetch('/api/impact-proof/health',{cache:'no-store'}).then(async r=>{const d=await r.json();setHealth(d);if(!r.ok&&d.code!=='DATABASE_NOT_CONFIGURED')throw Error(d.code||'IMPACT_HEALTH_UNAVAILABLE')}).catch(e=>setHealthError(e.message));},[]);
 const ops={assigned:assignments.filter(a=>a.status==='assigned').length,inProgress:assignments.filter(a=>a.status==='in_progress').length,blocked:assignments.filter(a=>a.status==='blocked').length};
 return <main className="min-h-screen bg-slate-50 text-slate-900"><header className="bg-slate-950 text-white"><div className="mx-auto max-w-7xl px-5 py-8"><div className="text-xs font-black uppercase tracking-[.25em] text-cyan-300">YCM ONE • MANAGEMENT CONTROL</div><div className="mt-2 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><h1 className="text-3xl font-black md:text-5xl">CEO Command Center</h1><p className="mt-2 max-w-3xl text-slate-300">One operating system. Separate control surfaces. Shared Family → Need → Service → Case → Outcome → Evidence → Audit universe.</p></div><a href="/impact-proof" className="rounded-2xl bg-cyan-400 px-5 py-3 text-sm font-black text-slate-950">Open Impact & Proof →</a></div></div></header>
 <section className="mx-auto max-w-7xl px-5 py-7"><div className="grid gap-4 md:grid-cols-4"><div className="rounded-3xl border bg-white p-5"><div className="text-xs font-bold text-slate-500">Architecture</div><div className="mt-2 text-3xl font-black">14</div><div className="text-xs text-slate-500">control sections</div></div><div className="rounded-3xl border bg-white p-5"><div className="text-xs font-bold text-slate-500">Operations</div><div className="mt-2 text-3xl font-black">{ops.assigned+ops.inProgress}</div><div className="text-xs text-slate-500">active assignments</div></div><div className="rounded-3xl border bg-white p-5"><div className="text-xs font-bold text-slate-500">Verified impact</div><div className="mt-2 text-3xl font-black">{impact?.reduce((n,x)=>n+(x.outcomes_verified||0),0) ?? '—'}</div><div className="text-xs text-slate-500">production records</div></div><div className="rounded-3xl border bg-white p-5"><div className="text-xs font-bold text-slate-500">Data connection</div><div className="mt-2 text-lg font-black">{impactError?'Pending DB/API':'Connected'}</div><div className="text-xs text-slate-500">{health?.ready?'All Impact tables detected':healthError||'Health check pending'}</div></div></div></section>
 <section className="mx-auto max-w-7xl px-5 pb-8"><div className="space-y-5">{sections.map(section=>{const ms=YCM_MODULES.filter(m=>m.section===section);return <section key={section} className="rounded-3xl border bg-white p-5 shadow-sm"><div className="flex flex-col justify-between gap-3 md:flex-row md:items-center"><div><div className="text-xs font-black uppercase tracking-[.18em] text-blue-700">Control section</div><h2 className="mt-1 text-2xl font-black">{section}</h2></div><div className="text-xs text-slate-500">{ms.length} module{ms.length!==1?'s':''}</div></div><div className="mt-5 grid gap-4 lg:grid-cols-2">{ms.map(m=><ModuleCard key={m.id} m={m}/>)}</div>{section==='Operations'&&<div className="mt-5 rounded-2xl bg-slate-50 p-4"><div className="grid gap-3 sm:grid-cols-3"><Stat label="Assigned" value={ops.assigned}/><Stat label="In progress" value={ops.inProgress}/><Stat label="Blocked" value={ops.blocked}/></div>{opsError&&<div className="mt-3 text-xs font-semibold text-amber-700">{opsError}</div>}<div className="mt-3 text-xs text-slate-500">Live assignment data is read from the existing work-assignment API.</div></div>}{section==='Impact & Proof'&&<div className="mt-5 rounded-2xl border border-blue-100 bg-blue-50 p-4"><div className="text-sm font-black text-blue-900">Evidence rule</div><p className="mt-1 text-sm leading-6 text-blue-950">Only consented records with explicit verification are counted as verified outcomes. Association is not converted into a causal claim automatically.</p>{impactError?<div className="mt-2 text-xs font-bold text-amber-700">{impactError} — UI remains empty until production data is connected.</div>:<div className="mt-2 text-xs font-bold text-blue-700">{impact?.length??0} geography rows loaded from production API.</div>}</div>}</section>})}</div></section>
 <section className="mx-auto max-w-7xl px-5 pb-12"><div className="rounded-3xl bg-slate-950 p-6 text-white"><div className="text-xs font-black uppercase tracking-[.18em] text-cyan-300">Unified lifecycle</div><div className="mt-4 flex flex-wrap gap-2">{YCM_LIFECYCLE.map((x,i)=><span key={x} className="rounded-xl bg-white/10 px-3 py-2 text-sm font-bold">{i+1}. {x}</span>)}</div></div></section></main>;
}
function ModuleCard({m}:{m:YCMModule}){return <article className="rounded-2xl border border-slate-200 p-5"><div className="flex items-start justify-between gap-3"><div><span className="text-xs font-black text-blue-700">MODULE {String(m.number).padStart(2,'0')}</span><h3 className="mt-1 text-xl font-black">{m.name}</h3></div><span className={'rounded-full border px-3 py-1 text-xs font-black '+statusClass[m.status]}>{statusLabel[m.status]}</span></div><p className="mt-2 text-sm leading-6 text-slate-600">{m.description}</p><div className="mt-4"><div className="flex justify-between text-xs font-bold"><span>Progress</span><span>{m.progress}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-blue-600" style={{width:m.progress+'%'}}/></div></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><div><div className="text-xs font-black uppercase tracking-wider text-slate-400">Key metrics</div><div className="mt-2 flex flex-wrap gap-1.5">{m.metrics.map(x=><span key={x} className="rounded-lg bg-slate-100 px-2 py-1 text-xs font-semibold">{x}</span>)}</div></div><div><div className="text-xs font-black uppercase tracking-wider text-slate-400">Next actions</div><ul className="mt-2 space-y-1 text-xs font-semibold text-slate-600">{m.nextBuild.map(x=><li key={x}>→ {x}</li>)}</ul></div></div></article>}
function Stat({label,value}:{label:string,value:number}){return <div className="rounded-2xl bg-white p-4 text-center"><div className="text-2xl font-black">{value}</div><div className="text-xs text-slate-500">{label}</div></div>}
