import {NextRequest,NextResponse} from 'next/server';
import postgres from 'postgres';
import {sessionCookieName,verifySession} from '../../lib/ycm-access-control';
import {requireVerifiedEmployee} from '../../lib/ycm-employee-verification';
export const runtime='nodejs';
const sess=(r:NextRequest)=>verifySession(r.cookies.get(sessionCookieName())?.value);
const db=()=>{const u=process.env.DATABASE_URL||process.env.POSTGRES_URL;return u?postgres(u,{max:3,prepare:false,connect_timeout:10,idle_timeout:20}):null};
const textMax=(v:unknown,max:number)=>v===undefined||v===null||typeof v==='string'&&v.trim().length<=max;
const validId=(v:unknown,max=120)=>typeof v==='string'&&v.trim().length>0&&v.trim().length<=max;
const validDateTime=(v:unknown)=>v===undefined||v===null||v===''||(typeof v==='string'&&!Number.isNaN(Date.parse(v)));
const sourceTypes=['family','case','document','lead','task'] as const;
const priorities=['low','normal','high','urgent'] as const;
const statuses=['assigned','accepted','in_progress','blocked','completed','reassigned'] as const;
export async function GET(r:NextRequest){const s=sess(r);if(!s)return NextResponse.json({success:false,code:'AUTHENTICATION_REQUIRED'},{status:401});const u=new URL(r.url),familyId=u.searchParams.get('familyId'),status=u.searchParams.get('status'),mine=u.searchParams.get('mine')==='true',sql=db();if(!sql)return NextResponse.json({success:false,code:'DATABASE_NOT_CONFIGURED'},{status:503});try{let rows:readonly unknown[];if(s.role==='employee'){rows=await sql`SELECT a.*,u.full_name assignee_name,t.name team_name FROM ycm_work_assignments a LEFT JOIN ycm_users u ON u.id=a.assigned_to LEFT JOIN ycm_teams t ON t.team_id=a.team_id WHERE a.assigned_to=(SELECT id FROM ycm_users WHERE user_id=${s.sub} LIMIT 1) AND (${status} IS NULL OR a.status=${status}) ORDER BY a.priority DESC,a.updated_at DESC LIMIT 200`;}else if(s.role==='team_lead'){rows=await sql`SELECT a.*,u.full_name assignee_name,t.name team_name FROM ycm_work_assignments a LEFT JOIN ycm_users u ON u.id=a.assigned_to LEFT JOIN ycm_teams t ON t.team_id=a.team_id WHERE t.manager_user_id=(SELECT id FROM ycm_users WHERE user_id=${s.sub} LIMIT 1) AND (${status} IS NULL OR a.status=${status}) ORDER BY a.priority DESC,a.updated_at DESC LIMIT 500`;}else{rows=await sql`SELECT a.*,u.full_name assignee_name,t.name team_name FROM ycm_work_assignments a LEFT JOIN ycm_users u ON u.id=a.assigned_to LEFT JOIN ycm_teams t ON t.team_id=a.team_id WHERE (${familyId} IS NULL OR a.family_id=${familyId}) AND (${status} IS NULL OR a.status=${status}) ORDER BY a.priority DESC,a.updated_at DESC LIMIT 500`;}return NextResponse.json({success:true,assignments:rows},{headers:{'Cache-Control':'private,no-store'}});}finally{await sql.end({timeout:3});}}
export async function POST(r:NextRequest){const s=sess(r);if(!s)return NextResponse.json({success:false,code:'AUTHENTICATION_REQUIRED'},{status:401});if(!['ceo','admin','management','team_lead'].includes(s.role))return NextResponse.json({success:false,code:'FORBIDDEN_ROLE_SCOPE'},{status:403});const b=await r.json().catch(()=>null) as {familyId?:string;sourceType?:'family'|'case'|'document'|'lead'|'task';sourceId?:string;assignedTo?:string;teamId?:string;priority?:'low'|'normal'|'high'|'urgent';reason?:string;dueAt?:string}|null;
if(!b?.familyId||!validId(b.familyId)||!b.sourceType||!sourceTypes.includes(b.sourceType)||!validId(b.sourceId)||(!validId(b.assignedTo||'')&&b.assignedTo!==undefined)||(!validId(b.teamId||'')&&b.teamId!==undefined)||!textMax(b.reason,2000)||!validDateTime(b.dueAt)||(b.priority!==undefined&&!priorities.includes(b.priority))) return NextResponse.json({success:false,code:'ASSIGNMENT_INPUT_INVALID'},{status:400});
if(!b?.familyId||!b.sourceType||!b.sourceId)return NextResponse.json({success:false,code:'ASSIGNMENT_FIELDS_REQUIRED'},{status:400});const sql=db();if(!sql)return NextResponse.json({success:false,code:'DATABASE_NOT_CONFIGURED'},{status:503});try{const actor=(await sql`SELECT id FROM ycm_users WHERE user_id=${s.sub} LIMIT 1`)[0]?.id||null;if(!actor)return NextResponse.json({success:false,code:'ACTOR_NOT_FOUND'},{status:403});let assignee=null;
if(s.role==='team_lead'){ if(!b.teamId)return NextResponse.json({success:false,code:'TEAM_SCOPE_REQUIRED'},{status:403}); const managedTeam=(await sql`SELECT 1 FROM ycm_teams WHERE team_id=${b.teamId} AND manager_user_id=${actor} AND status='active' LIMIT 1`)[0]; if(!managedTeam)return NextResponse.json({success:false,code:'TEAM_SCOPE_FORBIDDEN'},{status:403}); if(b.assignedTo)return NextResponse.json({success:false,code:'TEAM_LEAD_CANNOT_DIRECT_ASSIGN_UNSCOPED_USER'},{status:403}); }
if(b.assignedTo){assignee=(await sql`SELECT id FROM ycm_users WHERE user_id=${b.assignedTo} AND role IN ('employee','admin','management','ceo') AND status='active' LIMIT 1`)[0]?.id||null;if(!assignee)return NextResponse.json({success:false,code:'ASSIGNEE_NOT_FOUND'},{status:400});}const a=(await sql`INSERT INTO ycm_work_assignments(family_id,source_type,source_id,assigned_by,assigned_to,team_id,priority,reason,due_at) VALUES(${b.familyId},${b.sourceType},${b.sourceId},${actor},${assignee},${b.teamId||null},${b.priority||'normal'},${b.reason||null},${b.dueAt||null}) RETURNING *`)[0];return NextResponse.json({success:true,assignment:a},{status:201});}finally{await sql.end({timeout:3});}}
export async function PATCH(r:NextRequest){const s=sess(r);if(!s)return NextResponse.json({success:false,code:'AUTHENTICATION_REQUIRED'},{status:401});const b=await r.json().catch(()=>null) as {assignmentId?:string;status?:'assigned'|'accepted'|'in_progress'|'blocked'|'completed'|'reassigned';note?:string;employeeResult?:string;employeeNote?:string;approvalStatus?:'approved'|'rejected'|'rework';reviewNote?:string;assignedTo?:string;priority?:'low'|'normal'|'high'|'urgent';dueAt?:string}|null;
if(!b?.assignmentId||!validId(b.assignmentId)||!textMax(b.note,2000)||!textMax(b.employeeResult,4000)||!textMax(b.employeeNote,4000)||!textMax(b.reviewNote,2000)||(!validId(b.assignedTo||'')&&b.assignedTo!==undefined)||!validDateTime(b.dueAt)||(b.status!==undefined&&!statuses.includes(b.status))||(b.priority!==undefined&&!priorities.includes(b.priority))||(b.approvalStatus!==undefined&&!['approved','rejected','rework'].includes(b.approvalStatus))) return NextResponse.json({success:false,code:'ASSIGNMENT_INPUT_INVALID'},{status:400});
if(!b?.assignmentId)return NextResponse.json({success:false,code:'ASSIGNMENT_ID_REQUIRED'},{status:400});const sql=db();if(!sql)return NextResponse.json({success:false,code:'DATABASE_NOT_CONFIGURED'},{status:503});try{const employeeGate=await requireVerifiedEmployee(sql,s.role,s.sub);if(employeeGate)return NextResponse.json(employeeGate,{status:403});const a=(await sql`SELECT * FROM ycm_work_assignments WHERE assignment_id=${b.assignmentId} LIMIT 1`)[0];if(!a)return NextResponse.json({success:false,code:'ASSIGNMENT_NOT_FOUND'},{status:404});const management=['ceo','admin','management'].includes(s.role),actor=(await sql`SELECT id FROM ycm_users WHERE user_id=${s.sub} LIMIT 1`)[0]?.id||null,own=actor&&actor===a.assigned_to,teamLead=s.role==='team_lead'&&!!(await sql`SELECT 1 FROM ycm_teams WHERE team_id=${a.team_id} AND manager_user_id=${actor} AND status='active' LIMIT 1`)[0];if(b.approvalStatus){if(!management&&!teamLead)return NextResponse.json({success:false,code:'APPROVAL_ACCESS_DENIED'},{status:403});if(b.approvalStatus==='approved'&&a.status!=='completed')return NextResponse.json({success:false,code:'WORK_MUST_BE_COMPLETED_BEFORE_APPROVAL'},{status:400});const reviewed=(await sql`UPDATE ycm_work_assignments SET approval_status=${b.approvalStatus},reviewed_by=${actor},reviewed_at=NOW(),review_note=${b.reviewNote||null},updated_at=NOW() WHERE assignment_id=${b.assignmentId} RETURNING *`)[0];return NextResponse.json({success:true,assignment:reviewed});}if(!management&&!teamLead&&!own)return NextResponse.json({success:false,code:'ASSIGNMENT_ACCESS_DENIED'},{status:403});if(!b.status)return NextResponse.json({success:false,code:'ASSIGNMENT_STATUS_REQUIRED'},{status:400});
const allowedTransitions:Record<string,string[]>={
 assigned:['accepted','reassigned'],
 accepted:['in_progress','reassigned','blocked'],
 in_progress:['blocked','completed','reassigned'],
 blocked:['accepted','in_progress','reassigned'],
 completed:[],
 reassigned:['accepted','in_progress']
};
if(String(a.status)===String(b.status)){return NextResponse.json({success:true,assignment:a});}
if(!(allowedTransitions[String(a.status)]||[]).includes(String(b.status))){
 return NextResponse.json({success:false,code:'ASSIGNMENT_STATUS_TRANSITION_INVALID',fromStatus:a.status,toStatus:b.status},{status:409});
}if(s.role==='employee'&&!['accepted','in_progress','blocked','completed'].includes(b.status))return NextResponse.json({success:false,code:'EMPLOYEE_STATUS_NOT_ALLOWED'},{status:403});if(s.role==='employee'&&(b.assignedTo||b.priority||b.dueAt||b.approvalStatus))return NextResponse.json({success:false,code:'EMPLOYEE_CANNOT_CHANGE_CONTROL_FIELDS'},{status:403});let assignee=a.assigned_to;if((management||teamLead)&&b.assignedTo){if(teamLead)return NextResponse.json({success:false,code:'TEAM_LEAD_CANNOT_REASSIGN_UNSCOPED_USER'},{status:403});assignee=(await sql`SELECT id FROM ycm_users WHERE user_id=${b.assignedTo} AND role IN ('employee','admin','management','ceo') AND status='active' LIMIT 1`)[0]?.id||null;if(!assignee)return NextResponse.json({success:false,code:'ASSIGNEE_NOT_FOUND'},{status:400});}const updated=(await sql`UPDATE ycm_work_assignments SET status=${b.status},assigned_to=${assignee},priority=${management&&b.priority?b.priority:a.priority},due_at=${management&&b.dueAt?b.dueAt:a.due_at},employee_result=${own&&s.role==='employee'?(b.employeeResult||a.employee_result):a.employee_result},employee_note=${own&&s.role==='employee'?(b.employeeNote||a.employee_note):a.employee_note},submitted_at=CASE WHEN ${own&&s.role==='employee'&&b.status==='completed'} THEN NOW() ELSE ${a.submitted_at} END,submitted_by=CASE WHEN ${own&&s.role==='employee'&&b.status==='completed'} THEN ${actor} ELSE ${a.submitted_by} END,approval_status=${own&&s.role==='employee'&&b.status==='completed'?'pending':a.approval_status},updated_at=NOW() WHERE assignment_id=${b.assignmentId} RETURNING *`)[0];await sql`INSERT INTO ycm_work_assignment_events(assignment_id,actor_user_id,from_status,to_status,note) VALUES(${b.assignmentId},${s.sub},${a.status},${b.status},${b.note||null})`;return NextResponse.json({success:true,assignment:updated});}finally{await sql.end({timeout:3});}}
