import { NextRequest, NextResponse } from 'next/server';
import postgres from 'postgres';
import { sessionCookieName, verifySession } from '../../lib/ycm-access-control';
export const runtime='nodejs';
const db=()=>{const u=process.env.DATABASE_URL||process.env.POSTGRES_URL;return u?postgres(u,{max:5,prepare:false,connect_timeout:10,idle_timeout:20}):null};
const auth=(r:NextRequest)=>{const s=verifySession(r.cookies.get(sessionCookieName())?.value);return s&&['ceo','admin','management'].includes(s.role)?s:null};
const bad=(code:string,status:number)=>NextResponse.json({success:false,code},{status});
export async function GET(r:NextRequest){const s=auth(r);if(!s)return bad('FORBIDDEN_ROLE_SCOPE',403);const u=new URL(r.url),state=u.searchParams.get('state'),district=u.searchParams.get('district'),block=u.searchParams.get('block'),v=u.searchParams.get('verified')!=='false',sql=db();if(!sql)return bad('DATABASE_NOT_CONFIGURED',503);try{const rows=await sql`SELECT state_code,district_code,block_code,COALESCE(village_code,'') village_code,COUNT(DISTINCT family_id)::int families_served,COUNT(DISTINCT case_id)::int cases_completed,COUNT(*) FILTER(WHERE verified)::int outcomes_verified,COUNT(*) FILTER(WHERE outcome_type='education_enrollment')::int education_enrollments,COUNT(*) FILTER(WHERE outcome_type='education_improvement' AND verified)::int education_improvements,COUNT(*) FILTER(WHERE outcome_type='scholarship_access' AND verified)::int scholarship_accesses,COUNT(*) FILTER(WHERE outcome_type='employment' AND verified)::int employment_outcomes,COUNT(*) FILTER(WHERE outcome_type='skill_completion' AND verified)::int skill_completions,COUNT(*) FILTER(WHERE outcome_type='government_service_access' AND verified)::int government_services_completed,COUNT(*) FILTER(WHERE outcome_type='document_completion' AND verified)::int document_completions,COUNT(*) FILTER(WHERE outcome_type='agriculture_outcome' AND verified)::int agriculture_outcomes FROM ycm_impact_records WHERE consent_captured=true AND ${v} = verified AND (${state} IS NULL OR state_code=${state}) AND (${district} IS NULL OR district_code=${district}) AND (${block} IS NULL OR block_code=${block}) GROUP BY state_code,district_code,block_code,village_code ORDER BY state_code,district_code,block_code,village_code`;return NextResponse.json({success:true,source:'postgresql',verifiedOnly:v,rows});}catch(e){return bad(e instanceof Error?e.message:'IMPACT_QUERY_FAILED',500)}finally{await sql.end({timeout:3})}}
export async function POST(r:NextRequest){const s=auth(r);if(!s)return bad('FORBIDDEN_ROLE_SCOPE',403);const b=await r.json().catch(()=>null);if(!b?.stateCode||!b?.districtCode||!b?.blockCode||!b?.outcomeType||!b?.consentCaptured)return bad('IMPACT_REQUIRED_FIELDS',400);const sql=db();if(!sql)return bad('DATABASE_NOT_CONFIGURED',503);try{const row=(await sql`INSERT INTO ycm_impact_records(family_id,member_id,case_id,state_code,district_code,block_code,village_code,outcome_type,baseline_value,current_value,unit,baseline_date,outcome_date,verified,verification_method,consent_captured,created_by) VALUES(${b.familyId||null},${b.memberId||null},${b.caseId||null},${b.stateCode},${b.districtCode},${b.blockCode},${b.villageCode||null},${b.outcomeType},${b.baselineValue??null},${b.currentValue??null},${b.unit||null},${b.baselineDate||null},${b.outcomeDate||null},${Boolean(b.verified)},${b.verificationMethod||null},true,${s.sub}) RETURNING impact_id`)[0];return NextResponse.json({success:true,impactId:row.impact_id},{status:201});}catch(e){return bad(e instanceof Error?e.message:'IMPACT_CREATE_FAILED',500)}finally{await sql.end({timeout:3})}}
