export type ModuleStatus = 'live' | 'partial' | 'planned';
export type YCMModule = { id:string; number:number; name:string; section:string; status:ModuleStatus; progress:number; description:string; metrics:string[]; nextBuild:string[]; };

export const YCM_MODULES:YCMModule[] = [
{id:'platform-overview',number:1,name:'Platform Overview',section:'Platform Overview',status:'live',progress:75,description:'Unified YCM One operating layer across citizen, family, Mitra and management workflows.',metrics:['Module health','Active workflows','Open risks'],nextBuild:['Live health aggregation','SLA alerts']},
{id:'operations',number:2,name:'Operations',section:'Operations',status:'partial',progress:65,description:'Assignment, case execution and operational queues connected to the shared case universe.',metrics:['Assigned','In progress','Blocked'],nextBuild:['SLA/TAT board','Escalation rules']},
{id:'family-360',number:3,name:'Family 360',section:'Family 360',status:'partial',progress:70,description:'Master family/member context shared across needs, services, documents, cases and outcomes.',metrics:['Families','Members','Verified facts'],nextBuild:['Consent ledger','Document vault']},
{id:'services',number:4,name:'Services',section:'Services',status:'live',progress:80,description:'Canonical service master and governance contract for scalable service discovery and execution.',metrics:['Services','Published','Paused'],nextBuild:['10k–50k registry scaling','Eligibility engine']},
{id:'documents',number:5,name:'Documents',section:'Documents',status:'partial',progress:65,description:'Document collection and validation layer linked to cases and service requirements.',metrics:['Documents','Validated','Rejected'],nextBuild:['Vault hardening','OCR provider connections']},
{id:'education',number:6,name:'Education',section:'Education',status:'partial',progress:55,description:'Education journey plus measurable baseline/intervention/follow-up outcome tracking.',metrics:['Students','Enrollments','Verified improvements'],nextBuild:['Block assessment capture','Institution verification']},
{id:'agriculture',number:7,name:'Agriculture',section:'Agriculture',status:'partial',progress:45,description:'Agri Desk workflows and outcome capture for farmer services and interventions.',metrics:['Farmers','Cases','Verified outcomes'],nextBuild:['Crop outcome schema','FPO integrations']},
{id:'finance',number:8,name:'Finance / Commission',section:'Finance/Commission',status:'partial',progress:60,description:'Transaction, commission, ledger and settlement architecture with reversal-safe calculations.',metrics:['Transactions','Commission','Settlement queue'],nextBuild:['Provider payout connection','Reconciliation']},
{id:'aeps',number:9,name:'AEPS',section:'AEPS',status:'partial',progress:45,description:'Provider-neutral AEPS contract and integration registry.',metrics:['Providers','Transactions','Provider status'],nextBuild:['Live provider','Reconciliation']},
{id:'crm',number:10,name:'CRM / Leads',section:'CRM/Leads',status:'partial',progress:60,description:'Lead, opportunity, referral and assignment workflows sharing the same case universe.',metrics:['Leads','Open opportunities','Conversions'],nextBuild:['WhatsApp lead intake','Pipeline automation']},
{id:'impact-proof',number:11,name:'Impact & Proof',section:'Impact & Proof',status:'partial',progress:45,description:'Evidence-first outcome measurement from State → District → Block → Village.',metrics:['Families','Verified outcomes','Evidence packets'],nextBuild:['Production DB/API','Evidence packet export']},
{id:'integrations',number:12,name:'Integrations',section:'Integrations',status:'partial',progress:50,description:'Central integration registry for government, payment, AEPS and partner providers.',metrics:['Registered','Connected','Pending'],nextBuild:['Health checks','Secrets rotation']},
{id:'security-audit',number:13,name:'Security / Audit',section:'Security/Audit',status:'partial',progress:60,description:'Session, authorization, audit and security policy foundations.',metrics:['Audit events','Privileged actions','Security alerts'],nextBuild:['MFA','Session revocation hardening']},
{id:'reports',number:14,name:'Reports',section:'Reports',status:'partial',progress:50,description:'Management reporting layer for operations, finance and verified impact.',metrics:['Reports','Scheduled','Evidence packets'],nextBuild:['Export service','Report permissions']},
{id:'village-opportunity-intelligence',number:15,name:'Village Opportunity Intelligence',section:'Village Intelligence',status:'partial',progress:65,description:'Village-level decision support for banking, insurance and government-school access gaps using verified geographic evidence.',metrics:['Villages','Opportunity score','High-priority gaps'],nextBuild:['Source-backed imports','Verification workflow','Map drill-down']},
];
export const YCM_LIFECYCLE=['Family','Need','Service','Documents','Case','Assignment','Provider','Result','Outcome','Evidence','Audit'];
