"use client";
import { useState } from "react";

type Plan={query:string;country:string;jurisdiction:string;category:string;sourcePriority:string[];verification:string[]};

export default function LegalSourcesSearchPage(){
 const [query,setQuery]=useState(""); const [country,setCountry]=useState("India"); const [jurisdiction,setJurisdiction]=useState("Rajasthan"); const [category,setCategory]=useState(""); const [plan,setPlan]=useState<Plan|null>(null); const [loading,setLoading]=useState(false);
 async function search(){setLoading(true);try{const r=await fetch("/api/legal-sources/search",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({query,country,jurisdiction,category})});const d=await r.json();if(r.ok)setPlan(d.plan);}finally{setLoading(false);}}
 return <main className="min-h-screen bg-slate-50 px-6 py-10 text-slate-900"><div className="mx-auto max-w-5xl"><div className="text-sm font-semibold tracking-[.2em] text-indigo-700">YCM ONE / LEGAL MITRA</div><h1 className="mt-2 text-4xl font-bold">Official Legal Source Search</h1><p className="mt-2 text-slate-600">Primary source first: law text, subordinate legislation, court information and legal-aid routing.</p>
 <section className="mt-8 rounded-3xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><div className="grid gap-4 md:grid-cols-2"><label className="text-sm font-semibold">Search query<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="BNS section, Act, legal issue, case..." className="mt-1 w-full rounded-xl border border-slate-300 px-4 py-3"/></label><label className="text-sm font-semibold">Category<input value={category} onChange={e=>setCategory(e.target.value)} placeholder="Criminal / Property / Cyber..." className="mt-1 w-full rounded-xl border border-slate-300 px-4 py-3"/></label><label className="text-sm font-semibold">Country<input value={country} onChange={e=>setCountry(e.target.value)} className="mt-1 w-full rounded-xl border border-slate-300 px-4 py-3"/></label><label className="text-sm font-semibold">Jurisdiction<input value={jurisdiction} onChange={e=>setJurisdiction(e.target.value)} className="mt-1 w-full rounded-xl border border-slate-300 px-4 py-3"/></label></div><button onClick={search} disabled={loading||!query.trim()} className="mt-5 rounded-xl bg-slate-950 px-6 py-3 font-bold text-white disabled:opacity-50">{loading?"Preparing…":"Search official sources →"}</button></section>
 {plan&&<section className="mt-6 space-y-5"><div className="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><h2 className="font-bold">Source Priority</h2><ol className="mt-3 list-decimal space-y-2 pl-5 text-sm">{plan.sourcePriority.map(x=><li key={x}>{x}</li>)}</ol></div><div className="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><h2 className="font-bold">Verification Checklist</h2><ul className="mt-3 list-disc space-y-2 pl-5 text-sm">{plan.verification.map(x=><li key={x}>{x}</li>)}</ul></div><div className="rounded-2xl bg-amber-50 p-4 text-sm leading-6 text-amber-900"><b>Production rule:</b> Search results are not legal advice. The system must preserve the primary-source URL, version/date and human lawyer review before relying on a proposition.</div></section>}
 </div></main>
}
