'use client';
import {useEffect,useState} from 'react';
type Emp={id:string;user_id:string;role:string;status:string;target_count:number;distributed_count:number;called_count:number;connected_count:number;no_answer_count:number;employee_hangup_count:number;customer_hangup_count:number;active_bucket:number};
export default function LeadControl(){
 const [data,setData]=useState<any>(null),[busy,setBusy]=useState(false),[count,setCount]=useState(200),[target,setTarget]=useState(200),[error,setError]=useState('');
 async function load(){const r=await fetch('/api/management/lead-control',{cache:'no-store'});const j=await r.json();if(!r.ok)throw Error(j.code);setData(j);setTarget(j.targetPerDay)}
 useEffect(()=>{load().catch(e=>setError(e.message))},[]);
 async function act(body:any){setBusy(true);setError('');try{const r=await fetch('/api/management/lead-control',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw Error(j.code);await load()}catch(e){setError(e instanceof Error?e.message:'FAILED')}finally{setBusy(false)}}
 return <main className="min-h-screen bg-slate-50 p-6 text-slate-900"><div className="mx-auto max-w-7xl">
 <div className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><div className="text-sm font-bold text-blue-700">YCM ONE · MANAGER</div><h1 className="text-3xl font-black">Lead Control Center</h1><p className="text-sm text-slate-500">Daily distribution, employee buckets and calling outcomes.</p></div><a href="/management" className="rounded-xl border bg-white px-4 py-2 text-sm font-bold">Management</a></div>
 {error&&<div className="mt-5 rounded-xl bg-red-50 p-4 text-red-700">{error}</div>}
 {data&&<><div className="mt-6 grid gap-4 md:grid-cols-4">{[['New Leads',data.summary.new_leads],['Distributed Today',data.summary.assigned_today],['Called Today',data.summary.called_today],['Connected Today',data.summary.connected_today]].map(([a,b])=><div className="rounded-2xl border bg-white p-5" key={String(a)}><div className="text-sm text-slate-500">{a}</div><div className="mt-1 text-3xl font-black">{b||0}</div></div>)}</div>
 <div className="mt-6 rounded-2xl border bg-white p-5"><div className="flex flex-wrap items-end gap-3"><label className="text-sm font-bold">Daily target (total)<input value={target} onChange={e=>setTarget(Number(e.target.value))} className="mt-1 block w-36 rounded-xl border p-2"/></label><button disabled={busy} onClick={()=>act({action:'set_target',targetPerDay:target})} className="rounded-xl bg-slate-950 px-4 py-2 text-sm font-bold text-white">Save target</button><label className="ml-auto text-sm font-bold">Distribute now<input value={count} onChange={e=>setCount(Number(e.target.value))} className="mt-1 block w-36 rounded-xl border p-2"/></label><button disabled={busy} onClick={()=>act({action:'distribute',count})} className="rounded-xl bg-blue-700 px-4 py-2 text-sm font-bold text-white">Distribute leads</button></div></div>
 <div className="mt-6 overflow-x-auto rounded-2xl border bg-white"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="p-4">Employee</th><th>Bucket</th><th>Given today</th><th>Called</th><th>Received</th><th>No answer</th><th>Emp. Hang-up</th><th>Customer Hang-up</th><th>Remaining</th></tr></thead><tbody>{data.employees.map((e:Emp)=><tr className="border-b" key={e.id}><td className="p-4 font-bold">{e.user_id}</td><td>{e.active_bucket}</td><td>{e.distributed_count}</td><td>{e.called_count}</td><td>{e.connected_count}</td><td>{e.no_answer_count}</td><td>{e.employee_hangup_count}</td><td>{e.customer_hangup_count}</td><td>{Math.max(0,data.targetPerDay-data.summary.assigned_today)}</td></tr>)}</tbody></table></div></>}</div></main>
}
