export type LegalCategory = { id:string; name:string; icon:string; description:string; subcategories:string[] };

export const LEGAL_CATEGORIES: LegalCategory[] = [
 {id:"criminal",name:"Criminal Law",icon:"⚖️",description:"Criminal complaints, FIR, bail, investigation and trial assistance.",subcategories:["Murder / homicide","Assault / hurt","Kidnapping / trafficking","Theft / robbery / dacoity","Cheating / fraud","Forgery / breach of trust","Sexual offences","Domestic violence","Dowry-related offences","Arms / explosives","Public order","Corruption","Organised crime","Other criminal matter"]},
 {id:"cyber",name:"Cyber Crime",icon:"💻",description:"Online fraud, identity theft, hacking, harassment and digital evidence.",subcategories:["UPI / payment fraud","Banking fraud","Phishing","Identity theft","Account hacking","Cyber stalking","Online harassment","Sextortion / blackmail","Fake profile","Data theft","Ransomware / malware","Crypto / virtual-asset fraud","E-commerce fraud"]},
 {id:"civil",name:"Civil Law",icon:"📜",description:"Civil disputes, notices, recovery, contracts and general litigation.",subcategories:["Money recovery","Contract dispute","Injunction","Civil notice","Damages","Specific performance","Civil appeal","Other civil matter"]},
 {id:"property",name:"Property & Land",icon:"🏠",description:"Land, possession, title, tenancy, inheritance and registration matters.",subcategories:["Land dispute","Boundary dispute","Encroachment","Possession","Title / ownership","Partition","Mutation","Registry / sale deed","Rent / tenancy","Lease","Inheritance / succession","Will / gift"]},
 {id:"family",name:"Family & Matrimonial",icon:"👨‍👩‍👧",description:"Marriage, divorce, maintenance, custody and family disputes.",subcategories:["Marriage","Divorce","Mutual consent divorce","Maintenance","Child custody","Guardianship","Domestic violence","Dowry / stridhan","Adoption","Inheritance","Family settlement"]},
 {id:"consumer",name:"Consumer",icon:"🛒",description:"Product, service, refund, warranty and consumer disputes.",subcategories:["Defective product","Poor service","Refund","Warranty","E-commerce","Builder / real estate","Insurance","Banking","Telecom","Travel"]},
 {id:"labour",name:"Labour & Employment",icon:"👷",description:"Employment, wages, termination, workplace and statutory benefit matters.",subcategories:["Unpaid salary","Termination","Wage dispute","PF / ESI","Gratuity","Bonus","Workplace harassment","Employment contract","Industrial dispute","Workplace accident"]},
 {id:"business",name:"Business & Corporate",icon:"🏢",description:"Company, partnership, contracts, compliance and commercial disputes.",subcategories:["Company / LLP","Partnership","Shareholder dispute","Director dispute","Commercial contract","Vendor dispute","Employment agreement","Insolvency","Corporate litigation","Compliance"]},
 {id:"ip",name:"Intellectual Property",icon:"™️",description:"Trademark, copyright, patent, design, software and brand matters.",subcategories:["Trademark","Copyright","Patent","Design","Trade secret","Software / technology","Domain dispute","Licensing","Infringement"]},
 {id:"tax",name:"Tax & Finance",icon:"💰",description:"Tax, banking, finance, insurance and financial regulatory matters.",subcategories:["Income tax","GST","Banking","Loan dispute","Insurance claim","Securities","Financial fraud","Tax notice"]},
 {id:"immigration",name:"Immigration",icon:"🌍",description:"Visa, immigration, residency, citizenship and cross-border matters.",subcategories:["Visa","Work permit","Student visa","Business immigration","Residency","Citizenship","Family immigration","Asylum / refugee"]},
 {id:"legal-aid",name:"Free Legal Aid",icon:"🆓",description:"Help identify possible legal-aid routes and connect to appropriate authorities.",subcategories:["Legal aid eligibility","DLSA / SLSA","NALSA","Legal aid lawyer","Lok Adalat","Mediation","Victim compensation","Legal awareness"]},
 {id:"documents",name:"Legal Documents",icon:"📄",description:"Assistance with information collection and document/application preparation.",subcategories:["Legal notice","Affidavit","Declaration","Undertaking","Agreement","Complaint application","Representation","RTI application","Power of attorney","Other document"]},
];

export const COUNTRIES = ["India","United States","United Kingdom","Canada","Australia","United Arab Emirates","Singapore","Other"];
