'use client';
import {useCallback,useEffect,useState} from 'react';
type Location={location_id:string;location_code:string;location_name:string;location_type:string;status:string};
type Item={item_id:string;sku:string;item_name:string;category:string;unit:string;reorder_level:number};
type Stock={location_id:string;location_name:string;item_id:string;sku:string;item_name:string;unit:string;quantity:number;average_unit_cost_paise:number;stock_value_paise:number;low_stock:boolean};
type Transfer={transfer_id:string;transfer_reference:string;status:string;source_location:string;destination_location:string;created_at:string;lines:Array<{sku:string;itemName:string;quantity:number}>};
type InventoryData={locations:Location[];items:Item[];stock:Stock[];transfers:Transfer[];summary:{locations:number;items:number;stockValuePaise:number;lowStock:number;inTransit:number}};
type ApiResponse={success?:boolean;code?:string;locationId?:string;itemId?:string;transferId?:string;transferReference?:string;status?:string;summary?:InventoryData['summary'];locations?:Location[];items?:Item[];stock?:Stock[];transfers?:Transfer[]};
const input='w-full rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm outline-none focus:border-cyan-500';
const button='rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50';
export default function SupplyInventoryPage(){
 const [data,setData]=useState<InventoryData>({locations:[],items:[],stock:[],transfers:[],summary:{locations:0,items:0,stockValuePaise:0,lowStock:0,inTransit:0}});
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [locationCode,setLocationCode]=useState(''),[locationName,setLocationName]=useState(''),[locationType,setLocationType]=useState('store');
 const [sku,setSku]=useState(''),[itemName,setItemName]=useState(''),[category,setCategory]=useState('IT Equipment'),[unit,setUnit]=useState('unit'),[reorderLevel,setReorderLevel]=useState('2');
 const [receiveLocation,setReceiveLocation]=useState(''),[receiveItem,setReceiveItem]=useState(''),[quantity,setQuantity]=useState('1'),[unitCost,setUnitCost]=useState('0'),[vendor,setVendor]=useState(''),[invoice,setInvoice]=useState('');
 const [source,setSource]=useState(''),[destination,setDestination]=useState(''),[transferItem,setTransferItem]=useState(''),[transferQuantity,setTransferQuantity]=useState('1');
 const load=useCallback(async()=>{try{const r=await fetch('/api/supply/inventory',{cache:'no-store'});const d=await r.json() as ApiResponse;if(!r.ok||!d.success)throw new Error(d.code||'INVENTORY_LOAD_FAILED');setData({locations:d.locations||[],items:d.items||[],stock:d.stock||[],transfers:d.transfers||[],summary:d.summary||{locations:0,items:0,stockValuePaise:0,lowStock:0,inTransit:0}});setError('');}catch(e){setError(e instanceof Error?e.message:'INVENTORY_LOAD_FAILED');}},[]);
 useEffect(()=>{const t=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(t);},[load]);
 const submit=async(payload:Record<string,unknown>)=>{setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/supply/inventory',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json() as ApiResponse;if(!r.ok||!d.success)throw new Error(d.code||'SUPPLY_ACTION_FAILED');setNotice(d.transferReference?('Transfer created: '+d.transferReference):'Saved successfully');await load();return true;}catch(e){setError(e instanceof Error?e.message:'SUPPLY_ACTION_FAILED');return false;}finally{setBusy(false);}};
 const money=(paise:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(paise/100);
 return <main className="min-h-screen bg-slate-50 text-slate-900"><header className="bg-slate-950 text-white"><div className="mx-auto max-w-7xl px-5 py-8"><a href="/command-center" className="text-xs font-bold text-cyan-300">← CEO Command Center</a><p className="mt-4 text-xs font-black uppercase tracking-[.25em] text-cyan-300">YCM ONE • OPERATIONS</p><h1 className="mt-2 text-3xl font-black md:text-5xl">Supply & Inventory Management</h1><p className="mt-3 max-w-3xl text-slate-300">Vendor purchase receipts, store-wise stock, asset distribution, inter-centre transfers and low-stock visibility.</p></div></header>
 <section className="mx-auto max-w-7xl space-y-6 px-5 py-7">
 {error&&<div role="alert" className="rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm font-bold text-rose-800">Error: {error}{error==='DATABASE_NOT_CONFIGURED'?' — configure the production database and apply migration 060 first.':''}</div>}
 {notice&&<div role="status" className="rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-bold text-emerald-800">{notice}</div>}
 <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{[{label:'Stores / Centres',value:data.summary.locations},{label:'Item catalogue',value:data.summary.items},{label:'Inventory value',value:money(data.summary.stockValuePaise)},{label:'Low stock lines',value:data.summary.lowStock},{label:'Transfers in transit',value:data.summary.inTransit}].map(k=><div key={k.label} className="rounded-2xl border bg-white p-5"><div className="text-xs font-bold text-slate-500">{k.label}</div><div className="mt-2 text-2xl font-black">{k.value}</div></div>)}</div>
 <div className="grid gap-5 lg:grid-cols-2">
 <section className="rounded-3xl border bg-white p-5"><h2 className="text-lg font-black">1. Add Store / Centre</h2><form className="mt-4 grid gap-3 sm:grid-cols-2" onSubmit={async e=>{e.preventDefault();if(await submit({action:'add_location',locationCode,locationName,locationType})){setLocationCode('');setLocationName('');}}}><input className={input} placeholder="Unique code e.g. BAYANA-01" value={locationCode} onChange={e=>setLocationCode(e.target.value)} required/><input className={input} placeholder="Store / Centre name" value={locationName} onChange={e=>setLocationName(e.target.value)} required/><select className={input} value={locationType} onChange={e=>setLocationType(e.target.value)}><option value="store">Store</option><option value="warehouse">Warehouse</option><option value="centre">Service Centre</option><option value="franchise">Franchise</option><option value="office">Office</option></select><button className={button} disabled={busy}>Save Location</button></form></section>
 <section className="rounded-3xl border bg-white p-5"><h2 className="text-lg font-black">2. Add Item / SKU</h2><form className="mt-4 grid gap-3 sm:grid-cols-2" onSubmit={async e=>{e.preventDefault();if(await submit({action:'add_item',sku,itemName,category,unit,reorderLevel:Number(reorderLevel)})){setSku('');setItemName('');}}}><input className={input} placeholder="SKU / Item code" value={sku} onChange={e=>setSku(e.target.value)} required/><input className={input} placeholder="Item name e.g. Mantra device" value={itemName} onChange={e=>setItemName(e.target.value)} required/><input className={input} placeholder="Category" value={category} onChange={e=>setCategory(e.target.value)} required/><input className={input} placeholder="Unit e.g. unit, box" value={unit} onChange={e=>setUnit(e.target.value)} required/><label className="text-xs font-semibold text-slate-600">Low-stock alert threshold<input className={input+' mt-1'} type="number" min="0" value={reorderLevel} onChange={e=>setReorderLevel(e.target.value)}/></label><button className={button} disabled={busy}>Save Item</button></form></section>
 <section className="rounded-3xl border bg-white p-5"><h2 className="text-lg font-black">3. Receive Purchased Stock</h2><p className="mt-1 text-sm text-slate-500">Record vendor, invoice, quantity and per-unit cost. Amounts are stored in paise.</p><form className="mt-4 grid gap-3 sm:grid-cols-2" onSubmit={async e=>{e.preventDefault();if(await submit({action:'receive_stock',locationId:receiveLocation,itemId:receiveItem,quantity:Number(quantity),unitCostPaise:Math.round(Number(unitCost)*100),vendorName:vendor,invoiceReference:invoice})){setQuantity('1');setVendor('');setInvoice('');}}}><select className={input} value={receiveLocation} onChange={e=>setReceiveLocation(e.target.value)} required><option value="">Select receiving location</option>{data.locations.map(x=><option key={x.location_id} value={x.location_id}>{x.location_name}</option>)}</select><select className={input} value={receiveItem} onChange={e=>setReceiveItem(e.target.value)} required><option value="">Select item</option>{data.items.map(x=><option key={x.item_id} value={x.item_id}>{x.sku} — {x.item_name}</option>)}</select><input className={input} type="number" min="1" max="1000000" value={quantity} onChange={e=>setQuantity(e.target.value)} placeholder="Quantity" required/><input className={input} type="number" min="0" step="0.01" value={unitCost} onChange={e=>setUnitCost(e.target.value)} placeholder="Unit cost ₹" required/><input className={input} value={vendor} onChange={e=>setVendor(e.target.value)} placeholder="Vendor name" required/><input className={input} value={invoice} onChange={e=>setInvoice(e.target.value)} placeholder="Invoice reference" required/><button className={button+' sm:col-span-2'} disabled={busy}>Receive Stock</button></form></section>
 <section className="rounded-3xl border bg-white p-5"><h2 className="text-lg font-black">4. Transfer Stock Between Centres</h2><p className="mt-1 text-sm text-slate-500">Source stock is reserved immediately. Destination stock increases only when receipt is confirmed.</p><form className="mt-4 grid gap-3 sm:grid-cols-2" onSubmit={async e=>{e.preventDefault();if(await submit({action:'transfer_stock',sourceLocationId:source,destinationLocationId:destination,lines:[{itemId:transferItem,quantity:Number(transferQuantity)}]})){setTransferQuantity('1');}}}><select className={input} value={source} onChange={e=>setSource(e.target.value)} required><option value="">From location</option>{data.locations.map(x=><option key={x.location_id} value={x.location_id}>{x.location_name}</option>)}</select><select className={input} value={destination} onChange={e=>setDestination(e.target.value)} required><option value="">To location</option>{data.locations.filter(x=>x.location_id!==source).map(x=><option key={x.location_id} value={x.location_id}>{x.location_name}</option>)}</select><select className={input} value={transferItem} onChange={e=>setTransferItem(e.target.value)} required><option value="">Select item</option>{data.items.map(x=><option key={x.item_id} value={x.item_id}>{x.sku} — {x.item_name}</option>)}</select><input className={input} type="number" min="1" max="1000000" value={transferQuantity} onChange={e=>setTransferQuantity(e.target.value)} required/><button className={button+' sm:col-span-2'} disabled={busy}>Create Transfer</button></form></section></div>
 <section className="rounded-3xl border bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-black">Stock by Location</h2><p className="mt-1 text-sm text-slate-500">Live inventory quantities and valuation.</p></div><button className="rounded-xl border px-4 py-2 text-sm font-bold" onClick={()=>void load()}>Refresh</button></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-slate-100 text-xs uppercase text-slate-600"><tr>{['Location','SKU / Item','Quantity','Average Unit Cost','Stock Value','Status'].map(x=><th className="px-3 py-3" key={x}>{x}</th>)}</tr></thead><tbody>{data.stock.map((x,i)=><tr key={x.location_id+x.item_id} className="border-b last:border-0"><td className="px-3 py-3 font-semibold">{x.location_name}</td><td className="px-3 py-3">{x.sku} — {x.item_name}</td><td className="px-3 py-3">{x.quantity} {x.unit}</td><td className="px-3 py-3">{money(Number(x.average_unit_cost_paise))}</td><td className="px-3 py-3">{money(Number(x.stock_value_paise))}</td><td className="px-3 py-3"><span className={x.low_stock?'rounded-full bg-amber-100 px-2 py-1 text-xs font-bold text-amber-800':'rounded-full bg-emerald-100 px-2 py-1 text-xs font-bold text-emerald-800'}>{x.low_stock?'Low stock':'Available'}</span></td></tr>)}{!data.stock.length&&<tr><td colSpan={6} className="px-3 py-8 text-center text-slate-500">No stock records yet. Add a location and item, then receive stock.</td></tr>}</tbody></table></div></section>
 <section className="rounded-3xl border bg-white p-5"><h2 className="text-xl font-black">Transfers & Centre Receipts</h2><div className="mt-4 space-y-3">{data.transfers.map(t=><div key={t.transfer_id} className="flex flex-col justify-between gap-3 rounded-2xl border p-4 md:flex-row md:items-center"><div><div className="font-black">{t.transfer_reference}</div><div className="mt-1 text-sm text-slate-600">{t.source_location} → {t.destination_location}</div><div className="mt-1 text-xs text-slate-500">{t.lines.map(l=>l.sku+' × '+l.quantity).join(', ')} • {new Date(t.created_at).toLocaleString()}</div></div><div className="flex items-center gap-3"><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold">{t.status}</span>{t.status==='in_transit'&&<button className={button} disabled={busy} onClick={()=>void submit({action:'confirm_transfer',transferId:t.transfer_id})}>Confirm Receipt</button>}</div></div>)}{!data.transfers.length&&<p className="py-6 text-center text-sm text-slate-500">No transfers recorded yet.</p>}</div></section>
 <p className="text-xs text-slate-500">Access is restricted by session role. This module records inventory movements and transfers; GST filing, vendor payment settlement and statutory accounting are separate finance controls.</p>
 </section></main>;
}
