'use client';
/* eslint-disable react-hooks/set-state-in-effect */
import {useEffect,useState} from 'react';

type Row={membership_id:string;user_id:string;full_name:string;mobile?:string;membership_segment:string;plan_code:string;amount_paise:number;validity_years:number;status:string;review_status:string;verification_reference?:string|null;review_note?:string|null;created_at:string};
export default function MembershipReviewPage(){
 const [rows,setRows]=useState<Row[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(''),[note,setNote]=useState<Record<string,string>>({});
 const load=async()=>{setLoading(true);setError('');try{const r=await fetch('/api/membership/review',{cache:'no-store'});const j=await r.json();if(!r.ok)throw Error(j.message||j.code||'REVIEW_QUEUE_UNAVAILABLE');setRows(j.queue||[]);}catch(e){setError(e instanceof Error?e.message:'REVIEW_QUEUE_UNAVAILABLE');}finally{setLoading(false);}};
 useEffect(()=>{void load();},[]);
 const decide=async(row:Row,decision:'approve'|'reject')=>{setBusy(row.membership_id+decision);setError('');try{const reference=(document.getElementById('ref-'+row.membership_id) as HTMLInputElement)?.value.trim();const r=await fetch('/api/membership/review',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({membershipId:row.membership_id,decision,verificationReference:reference,reviewNote:note[row.membership_id]||''})});const j=await r.json();if(!r.ok)throw Error(j.message||j.code||'REVIEW_FAILED');await load();}catch(e){setError(e instanceof Error?e.message:'REVIEW_FAILED');}finally{setBusy('');}};
 return <main className="min-h-screen bg-slate-50 text-slate-900"><header className="bg-slate-950 text-white"><div className="mx-auto max-w-6xl px-5 py-8"><div className="text-xs font-black uppercase tracking-[.2em] text-cyan-300">YCM ONE • HIGH MANAGEMENT</div><h1 className="mt-2 text-3xl font-black md:text-5xl">Special Membership Review</h1><p className="mt-2 max-w-3xl text-slate-300">Only Management / CEO can approve. Employees, Sales and Team Leads do not receive approval authority.</p></div></header>
 <section className="mx-auto max-w-6xl px-5 py-7"><div className="mb-5 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm leading-6 text-amber-950"><b>Rule:</b> ₹99 special membership starts as 1-year pending review. Approval changes it to 2 years. Widow review may use the controlled death-certificate case/document reference. Defense review does not require YCM to collect or connect to defense/government source data.</div>
 {error&&<div className="mb-4 rounded-xl bg-red-50 p-3 text-sm font-bold text-red-700">{error}</div>}
 <div className="space-y-4">{loading?<div className="rounded-2xl border bg-white p-5">Loading review queue…</div>:!rows.length?<div className="rounded-2xl border bg-white p-8 text-center text-slate-500">No pending special memberships.</div>:rows.map(row=><article key={row.membership_id} className="rounded-3xl border bg-white p-5 shadow-sm"><div className="flex flex-col justify-between gap-3 md:flex-row"><div><div className="text-xs font-black uppercase tracking-wider text-slate-500">{row.membership_segment==='widow_household'?'Widow Household':'Defense Family'}</div><h2 className="mt-1 text-xl font-black">{row.full_name}</h2><p className="text-sm text-slate-500">{row.mobile||row.user_id} • ₹{Number(row.amount_paise/100).toLocaleString('en-IN')} • Current plan: {row.validity_years} year</p></div><span className="h-fit rounded-full bg-amber-100 px-3 py-1 text-xs font-black text-amber-800">PENDING REVIEW</span></div>
 <div className="mt-4 grid gap-3 md:grid-cols-2"><label><span className="mb-1 block text-xs font-black text-slate-500">{row.membership_segment==='widow_household'?'Death certificate / case reference':'Management verification reference'}</span><input id={'ref-'+row.membership_id} placeholder="Document/case reference (not raw document data)" className="w-full rounded-xl border px-3 py-2 text-sm"/></label><label><span className="mb-1 block text-xs font-black text-slate-500">Review note</span><input value={note[row.membership_id]||''} onChange={e=>setNote(v=>({...v,[row.membership_id]:e.target.value}))} placeholder="Reason / verification note" className="w-full rounded-xl border px-3 py-2 text-sm"/></label></div>
 <div className="mt-4 flex flex-wrap gap-2"><button disabled={!!busy} onClick={()=>void decide(row,'approve')} className="rounded-xl bg-emerald-600 px-5 py-3 text-sm font-black text-white disabled:opacity-50">{busy===row.membership_id+'approve'?'Approving…':'Approve → 2 Years'}</button><button disabled={!!busy} onClick={()=>void decide(row,'reject')} className="rounded-xl border border-red-200 bg-red-50 px-5 py-3 text-sm font-black text-red-700 disabled:opacity-50">{busy===row.membership_id+'reject'?'Rejecting…':'Reject'}</button></div></article>)}</div></section></main>;
}